### ISSUE TITLE
ground truth for spotlight locating

### ISSUE THREAD

**Issue by ruoyuxie** [MozerWang/Loong#8]
Hello! Thank you for your excellent work. Could you please provide some guidance on where to find ground truth data for the spotlight locating task?

**Comment by MozerWang** [comment]
Sorry for the late reply! 

For financial reports, we pre-defined several commonly used attributes (such as total income, total profit, and equity) and then utilized GPT-4 to perform information extraction tasks. We constructed specific queries for each attribute to extract relevant answers. To ensure the quality of annotations, we implemented evidence recall and rechecking mechanisms. We also manually checked the extraction quality of GPT4o

In the case of judgment documents, we were able to directly perform document splicing due to the presence of natural labels within the text.

**Comment by ruoyuxie** [comment]
Thank you!!
