### ISSUE TITLE
构造context时，进行两次shuffle的原因是什么

### ISSUE THREAD

**Issue by YanShuang17** [MozerWang/Loong#9]
作者您好，非常感谢这份开源工作，我有一个问题：

在`https://github.com/MozerWang/Loong/blob/main/src/utils/prompt.py`的93行和101行，进行了两次shuffle，请问93行处的shuffle的意义是什么呢？ 

@MozerWang

**Comment by MozerWang** [comment]
It's been a while, so the answer may not be accurate. 

This is an operation for financial report documents. In each financial report case, the docs are in chronological order. If it is not shuffled in advance, only the latest document will be intercepted when the length limit is exceeded. Therefore, we shuffle the documents so that the intercepted documents are random.
